/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;

/**
 *
 * @author user
 */
import Codes.OTP_Cipher;
import Codes.Cesar_Cipher;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
public class MainFrame extends javax.swing.JFrame {
    //create an object to use the methods of algorathim class
    OTP_Cipher otp_class = new OTP_Cipher();
    Cesar_Cipher cesar_class = new Cesar_Cipher();
    
    ButtonGroup group = new ButtonGroup();

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        //add radio buttons in one group
        group.add(otp);
        group.add(cesar);
        group.add(hill);
        group.add(aes);
        group.add(des);
        otp.setSelected(true);
        
        
    }
    
    //Get the selected button in the group
    public String getSelectedButton(){
        for (Enumeration<AbstractButton> buttons = group.getElements(); buttons.hasMoreElements();){
            AbstractButton button = buttons.nextElement();
            if (button.isSelected()) {
                return button.getText();
            }
        }
        return null;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main_panel = new javax.swing.JPanel();
        algo_panel = new javax.swing.JPanel();
        otp = new javax.swing.JRadioButton();
        cesar = new javax.swing.JRadioButton();
        hill = new javax.swing.JRadioButton();
        aes = new javax.swing.JRadioButton();
        des = new javax.swing.JRadioButton();
        text_panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        text_TA = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        kw = new javax.swing.JTextField();
        ciDe_text_panel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ciDe_text_TA = new javax.swing.JTextArea();
        cipher_button = new javax.swing.JButton();
        decipher_button = new javax.swing.JButton();
        notification = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        algo_panel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204)), "Algorithm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        otp.setText("OTP");

        cesar.setText("Cesar");
        cesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cesarActionPerformed(evt);
            }
        });

        hill.setText("Hill");

        aes.setText("AES");

        des.setText("DES");

        javax.swing.GroupLayout algo_panelLayout = new javax.swing.GroupLayout(algo_panel);
        algo_panel.setLayout(algo_panelLayout);
        algo_panelLayout.setHorizontalGroup(
            algo_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(algo_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(otp)
                .addGap(35, 35, 35)
                .addComponent(cesar)
                .addGap(35, 35, 35)
                .addComponent(hill)
                .addGap(35, 35, 35)
                .addComponent(aes)
                .addGap(35, 35, 35)
                .addComponent(des)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        algo_panelLayout.setVerticalGroup(
            algo_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(algo_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(algo_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(otp)
                    .addComponent(cesar)
                    .addComponent(hill)
                    .addComponent(aes)
                    .addComponent(des))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        text_panel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204)), "Plain/Cipher Text", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        text_TA.setColumns(20);
        text_TA.setRows(5);
        jScrollPane1.setViewportView(text_TA);

        javax.swing.GroupLayout text_panelLayout = new javax.swing.GroupLayout(text_panel);
        text_panel.setLayout(text_panelLayout);
        text_panelLayout.setHorizontalGroup(
            text_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(text_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        text_panelLayout.setVerticalGroup(
            text_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(text_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("KeyWord: ");

        kw.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                kwKeyPressed(evt);
            }
        });

        ciDe_text_panel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204)), "Cipher/Decipher Text", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        ciDe_text_TA.setColumns(20);
        ciDe_text_TA.setRows(5);
        jScrollPane2.setViewportView(ciDe_text_TA);

        cipher_button.setText("Cipher");
        cipher_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cipher_buttonActionPerformed(evt);
            }
        });

        decipher_button.setText("Decipher");
        decipher_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decipher_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ciDe_text_panelLayout = new javax.swing.GroupLayout(ciDe_text_panel);
        ciDe_text_panel.setLayout(ciDe_text_panelLayout);
        ciDe_text_panelLayout.setHorizontalGroup(
            ciDe_text_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ciDe_text_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(ciDe_text_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cipher_button)
                    .addComponent(decipher_button))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        ciDe_text_panelLayout.setVerticalGroup(
            ciDe_text_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ciDe_text_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ciDe_text_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(ciDe_text_panelLayout.createSequentialGroup()
                        .addComponent(cipher_button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(decipher_button))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout main_panelLayout = new javax.swing.GroupLayout(main_panel);
        main_panel.setLayout(main_panelLayout);
        main_panelLayout.setHorizontalGroup(
            main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(main_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(algo_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(main_panelLayout.createSequentialGroup()
                        .addComponent(text_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(notification, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(kw, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(main_panelLayout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(ciDe_text_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(217, Short.MAX_VALUE))
        );
        main_panelLayout.setVerticalGroup(
            main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(main_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(algo_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(main_panelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(text_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(main_panelLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(kw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(notification, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39)
                .addComponent(ciDe_text_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cesarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cesarActionPerformed

    private void cipher_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cipher_buttonActionPerformed
        // TODO add your handling code here:
        String plain_text = text_TA.getText();
        String keyword = kw.getText();
        
        //check the selected radio button
        switch(getSelectedButton()){
            case "OTP":
                ciDe_text_TA.setText(otp_class.encryption(plain_text, keyword));
                break;
            case "Cesar":
                ciDe_text_TA.setText(cesar_class.encryption(plain_text, Integer.parseInt(keyword)));
                break;
        }
        
    }//GEN-LAST:event_cipher_buttonActionPerformed

    private void decipher_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decipher_buttonActionPerformed
        // TODO add your handling code here:
        String cipher_text = text_TA.getText();
        String keyword = kw.getText();
        //check the selected radio button
        switch(getSelectedButton()){
            case "OTP":
                ciDe_text_TA.setText(otp_class.decryption(cipher_text, keyword));
                break;
            case "Cesar":
                ciDe_text_TA.setText(cesar_class.decryption(cipher_text, Integer.parseInt(keyword)));
                break;
        }
   
    }//GEN-LAST:event_decipher_buttonActionPerformed

    private void kwKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kwKeyPressed
        // in case of choosing Cesar cipher the only acceptable values in keyword are numbers
        if(getSelectedButton() == "Cesar"){
            char c = evt.getKeyChar();
            if(Character.isLetter(c)){
                kw.setEditable(false);
                notification.setText("Numbers only");
            }
            else{
                kw.setEditable(true);
            }
        }
    }//GEN-LAST:event_kwKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton aes;
    private javax.swing.JPanel algo_panel;
    private javax.swing.JRadioButton cesar;
    private javax.swing.JTextArea ciDe_text_TA;
    private javax.swing.JPanel ciDe_text_panel;
    private javax.swing.JButton cipher_button;
    private javax.swing.JButton decipher_button;
    private javax.swing.JRadioButton des;
    private javax.swing.JRadioButton hill;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField kw;
    private javax.swing.JPanel main_panel;
    private javax.swing.JLabel notification;
    private javax.swing.JRadioButton otp;
    private javax.swing.JTextArea text_TA;
    private javax.swing.JPanel text_panel;
    // End of variables declaration//GEN-END:variables
}
